### ISSUE TITLE
added crop and server crashes (no crash report)

### ISSUE THREAD

**Issue by Nicon4454** [BlakeBr0/MysticalCustomization#8]
THIS IS HARD TO READ so i made a [pastebin](https://pastebin.com/ezur6yxd)

**Describe the bug**
i created a json file (like the example file) 
`{
    "name": "Prudentium Essence",
    "type": "resource",
    "tier": "mysticalagriculture:2",
    "ingredient": {
        "item": "mysticalagriculture:prudentium_essence"
    },
    "color": "075209",
    "textures": {
        "flower": "mysticalagriculture:block/flower_dust",
        "essence": "mysticalagriculture:item/essence_dust"
    }
}`

From the consol 
`[10:46:43] [main/WARN] [ne.mi.re.ForgeRegistry/REGISTRIES]: Registry Item: Override did not have an associated owner object. Name: mysticalagriculture:prudentium_essence Value: air
[10:46:43] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
java.lang.RuntimeException: One of more entry values did not copy to the correct id. Check log for details!
        at net.minecraftforge.registries.ForgeRegistry.sync(ForgeRegistry.java:598) ~[forge:?] {re:classloading}
        at net.minecraftforge.registries.GameData.loadRegistry(GameData.java:651) ~[forge:?] {re:classloading}
        at net.minecraftforge.registries.GameData.freezeData(GameData.java:282) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.finishMods(ModLoader.java:220) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:46) ~[forge:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275] {}
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.4-35.1.13.jar:35.1] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.4-35.1.13.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.4-35.1.13.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.4-35.1.13.jar:?] {}
` 

**To Reproduce**

**Expected behavior**
to have a seed be created for the essence

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft:1.16.4
 - Forge:35.1.13
 - Cucumber:1.15.4-4.1.5
 - Mystical Agriculture:1.16.4-4.1.3
 - Mystical Customization:1.16.4-2.1.1

**Comment by BlakeBr0** [comment]
Did you try to add Prudentium seeds? Since there's already a Prudentium Essence item it will try to override that, which will break other things.

**Comment by BlakeBr0** [comment]
Is the name of the file 'prudentium'? If so it'll conflict with the Prudentium Essence item when it tries to create the essence for this crop.

**Comment by Nicon4454** [comment]
ok i will try a different name and see if that makes a difference

**Comment by Nicon4454** [comment]
that is what it was thank you.
